---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[s3_file::default]
    attributes:
